FROM tensorflow/tensorflow:2.3.0

WORKDIR /tf
RUN apt-get update && apt-get install -y git

# For onnx2keras compatibility issue
ENV TF_KERAS=1  
ENV TF_CPP_MIN_LOG_LEVEL=3

COPY Examples/dlconvert_examples/dlconvert_requirements.txt /tf/
COPY requirements.txt /tf/

RUN pip install -r dlconvert_requirements.txt
RUN pip install -r requirements.txt

COPY src/aup /tf/src/aup
COPY tests/dlconvert /tf/tests/dlconvert
COPY setup.py README.md /tf/
RUN cd /tf/ && python setup.py -q install
RUN cd /tf/tests/dlconvert/data && ./prepare_docker.sh

VOLUME /tf/htmlcov

CMD coverage run --source dlconvert -m pytest tests; coverage html